package kprint
/**
 * THIS CLASS IS USED IN CONJUNCTION WITH THE PAGE CLASS
 * It is set to be generated by adding it to the Constructor of the Page
 */
class FormatBar(_size : Int = 200) {
    private val bText : String = cText(_size)
    override fun toString(): String {
        return this.bText
    }
    private fun cText(_size : Int) : String {
        val ret = StringBuilder()
        var last = 0
        for (e in 1.._size) {
            val str : String = e.toString()
            ret.append(str[str.length - 1])
        }
        ret.append("\n")
        for (n in 1.._size / 10) {
            for (k in 1..9) {
                if (k == 1 || last > 0) {
                    if (k == 1) {
                        ret.append(0)
                    }
                    last--
                    continue
                }

                ret.append(' ')
            }
            ret.append(n)
            last = n.toString().length
        }
        return ret.append(0).toString()
    }
}
